"""update like table to use composite primary key

Revision ID: 6cd516d54535
Revises: f4269c556153
Create Date: 2025-05-14 12:24:56.671844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6cd516d54535'
down_revision = 'f4269c556153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.alter_column('board_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_constraint('board_user_id_board_name_key', type_='unique')

    with op.batch_alter_table('follow_stream', schema=None) as batch_op:
        batch_op.alter_column('stream_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('follow_stream_board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('added_at')

    with op.batch_alter_table('pin', schema=None) as batch_op:
        batch_op.drop_constraint('pin_board_id_post_id_key', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('pin', schema=None) as batch_op:
        batch_op.create_unique_constraint('pin_board_id_post_id_key', ['board_id', 'post_id'])

    with op.batch_alter_table('follow_stream_board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('id')

    with op.batch_alter_table('follow_stream', schema=None) as batch_op:
        batch_op.alter_column('stream_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.create_unique_constraint('board_user_id_board_name_key', ['user_id', 'board_name'])
        batch_op.alter_column('board_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
